apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: custom.csi.driver
spec:
  attachRequired: false
  podInfoOnMount: true
  fsGroupPolicy: File
  storageCapacity: true
  volumeLifecycleModes:
    - Persistent
