apiVersion: v1
entries:
  lsdisk:
  - apiVersion: v2
    appVersion: v1.0.0
    created: "2025-11-23T14:32:07.568715676+03:30"
    description: A Helm chart for the lsdisk CSI driver
    digest: bdfeb9d56f1530c6c27bb0b66bb40fd4256fba5b00a1cb8e95f0f9368bbf2416
    icon: https://raw.githubusercontent.com/danialnabiyan/lsdisk-csi/main/deploy/lsdisk/files/icon.png
    name: lsdisk
    type: application
    urls:
    - lsdisk-2.0.5.tgz
    version: 2.0.5
  - apiVersion: v2
    appVersion: v1.0.0
    created: "2025-10-28T11:07:54.972838575+03:30"
    description: A Helm chart for the lsdisk CSI driver
    digest: 538f121dda478c903013b18666ab47352cdac8ad02b4d337756f9e64176a38c1
    icon: https://raw.githubusercontent.com/danialnabiyan/lsdisk-csi/main/deploy/lsdisk/files/icon.png
    name: lsdisk
    type: application
    urls:
    - lsdisk-2.0.4.tgz
    version: 2.0.4
generated: "2025-11-23T14:32:07.560519663+03:30"
